version: "3"

services:

  ubuntu:
    container_name: ubuntu_polemarch
    build: .
    ports:
      - 8080:8080

  python:
    container_name: malicious-server
    image: python:3
    volumes:
      - ./poc:/usr/src/myapp
    ports:
      - 3005:80
    working_dir: /usr/src/myapp
    command: sh -c "python tar.py && cd tar && python -m http.server 80"

