version: "3"

services:

  polemarch:
    container_name: polemarch
    build: .
    ports:
      - 8180:8080

  python:
    container_name: malicious-server
    image: python:3
    volumes:
      - .:/usr/src/myapp
    ports:
      - 3005:80
    working_dir: /usr/src/myapp
    command: sh -c "cd poc && python tar.py && cd tar && python -m http.server 80"

